name: sanity-SingleDeploymentwithDataTransfer-IPIPIP

tasks: 
    
# Deploy Tibcotunnelroute CR
  - name: tibcotunnelroute-status-withFunctions
    type: foreground
    templates:
     - input: "./resources/services/tibcotunnelrouteCR.yaml"
       output: "./generated/tibcotunnelrouteCR.yaml"
    exec: 
     timeout: 30s
     script: 
        cmd: "${ENV.fnSh}"
        args: ["deployResourse", "./generated/tibcotunnelrouteCR.yaml"]
        capture:
         stdout:
           - name: output
             match: "((?s).*)"
         stderr:
            - name: outerr
              match: "((?s).*)"
    expect:
     - name: status
       operator: equal
       value: 0
      
# Status of Tibcotunneroute CR
  - name: tibcotunnelroute-status
    type: foreground
    exec: 
      timeout: 30s
      script: 
        cmd: "kubectl"
        args: ["get", "tibcotunnelroute", "${META_DATA_NAME}", "-n", "${NAMESPACE_TENANT}", "-o", "json"]
        capture: 
          stdout: 
            - name : status_cr
              matchType: jsonpath
              match: "{.status.resource.state}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: status_cr
        operator: containsStr
        value: "processed"

# Deploy ClientAppn Deployments
  - name: deployClientApp
    type: foreground
    templates: 
      - input: "./resources/services/client-app.yaml"
        output: "./generated/client-app.yaml"
    exec: 
      timeout: 2m
      script:
        cmd: "kubectl"
        args: ["apply", "-f", "./generated/client-app.yaml"]
    expect:
      - name: status
        operator: equal
        value: 0

# Status of Client Applications
  - name: status_of-clientAppn
    type: foreground
    exec: 
      timeout: 30s
      script: 
        cmd: "kubectl"
        args: ["get", "pods", "-n", "${NAMESPACE_TENANT}", "-o", "json", "--selector=app=http"]
        capture:
          stdout:
            - name: running_state
              matchType: jsonpath
              match: "{.items[*].status.phase}"
            - name: capture_pod_name
              matchType: jsonpath
              match: "{.items[0].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: running_state
        operator: contains
        value: "Running"
      - name: running_state
        operator: notContains
        value: "Pending"
    repeat:
      count: -1
      until: success
      sleep: 20ms  

# Tibtunnel Connect
  - name: tibtunnelConnect
    type: background
    exec:
      script:
        cmd: "/bin/bash"
        args: ["-c", "timeout 60s ./tibtunnel connect -d --remote-debug -s ${CONTAINER_PORT}:${ONPREMISE_IP}:${ONPREMISE_PORT} https://${FQDN}/${ENDPOINT} -l ./tibtunnelLog" ]

# Tunnel Status b/w tibtunnel and Client App 
  - name: checkTunnelStatus
    type: foreground
    timeout: 20s
    exec:
      script:
        cmd: "kubectl"
        args: ["exec", "${status_of-clientAppn.capture_pod_name}", "-n${NAMESPACE_TENANT}", "-c", "main", "--", "curl", "-s", "localhost:7778/v1/tunnel/status"]
        capture:
          stdout: 
            - name: output
              match: "((?s).*)"          
    expect:
      - name: output
        operator: containsStr
        value: "\"isConnected\":true"
      - name: output
        operator: notContainsStr
        value: "false"
    repeat:
      count: -1
      until: success
      sleep: 10ms  
        
# Start On-Prem Appn with IP-Address
  - name: startOnpremAppn
    type: background
    exec:
      script:
        cmd: "/bin/bash"
        args: ["-c", "timeout 30s ./tcp-server -d -a ${ONPREMISE_IP}:${ONPREMISE_PORT} >> ./tcpserverLog"]
        capture:
          stdout:
            - name: output
              match: "((?s).*)"
          stderr:
            - name: stderr
              match: "((?s).*)"
    expect:
      - name: stderr
        operator: containsStr
        value: "TCP server started"

# Communication b/w ClientPod and On-Prem Appn by sending Data
  - name: sendData
    type: foreground
    exec:
      timeout: 30s
      script:
        cmd: "kubectl"
        args: ["exec", "${status_of-clientAppn.capture_pod_name}", "-n${NAMESPACE_TENANT}", "-c", "main", "--", "/test/tcp-client", "-a", "${ONPREMISE_IP}:${ONPREMISE_PORT}"]
        capture:
          stdout:
            - name: output
              match: "((?s).*)"
          stderr:
            - name: stderr
              match: "((?s).*)"              
    expect:
      - name: stderr
        operator: containsStr
        value: "Successfully send/received 1.0KiB"
    repeat:
      count: -1
      until: success
      sleep: 2s    
  - name: sleepCommand
    type: foreground
    exec:
      script:
        cmd: "sleep"
        args: ["80"]

teardown: 

# Delete the Tibcotunneroute CR
  - name: delete_yaml_file
    type: foreground
    exec: 
      timeout: 1m
      script:
        cmd: "kubectl"
        args: ["delete", "-f", "./generated/tibcotunnelrouteCR.yaml"]
    expect:
      - name: status
        operator: equal
        value: 0

# Delete the ClientApp Deployments
  - name: delete_yaml_file
    type: foreground
    exec: 
      timeout: 1m
      script:
        cmd: "kubectl"
        args: ["delete", "-f", "./generated/client-app.yaml"]
    expect:
      - name: status
        operator: equal
        value: 0
    repeat:
      count: -1
      until: success
      sleep: 10ms

        
# Verify Tibcotunneroute CR Deletion
  - name: confirm_deletionCR
    type: foreground
    exec: 
      timeout: 1m
      script: 
        cmd: "kubectl"
        args: ["get", "tibcotunnelroute", "-n", "${NAMESPACE_TENANT}", "-o", "json"]
        capture:
          stdout: 
            - name: confirm_deleteCR
              matchType: jsonpath
              match: "{.items[*].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: confirm_deleteCR
        operator: notContainsStr
        value: "${META_DATA_NAME}"

# Verify ClientApp Deployments deletion
  - name: confirm_deletionA
    type: foreground
    exec: 
      timeout: 1m
      script: 
        cmd: "kubectl"
        args: ["get", "deploy", "-n", "${NAMESPACE_TENANT}", "-o", "json"]
        capture:
          stdout: 
            - name: confirm_deleteA
              matchType: jsonpath
              match: "{.items[*].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: confirm_deleteA
        operator: notContainsStr
        value: "${META_DATA_NAME}"
    repeat:
      count: -1
      until: success
      sleep: 10ms 
